---
- name: Installing snap
  become: true
  register: installation
  apt:
    pkg: snap
    state: latest

- name: Installing microk8s with snap
  become: true
  command: snap install microk8s --classic
